language: cpp
cache: apt
compiler: g++

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq build-essential cmake git-core
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get install -qq g++-4.9
 - sudo export CXX="g++-4.9"
 - sudo add-apt-repository -y ppa:boost-latest/ppa && sudo apt-get update -q && sudo apt-get install -y libboost1.55-all-dev
 - sudo apt-get install -qq libssl-dev libssh2-1-dev
 - sudo apt-get install -qq freeglut3 freeglut3-dev libglew1.5 libglew1.5-dev libglu1-mesa libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev


branches:
  only:
    - master

before_script:
 - chmod +x ./build_linux.sh 

script: ./build_linux.sh

