language: cpp
cache: apt
compiler: gcc

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq build-essential cmake git-core
 - sudo apt-get install -qq pkg-config mono-devel
 - sudo apt-get install -qq mysql-client libmysqlclient-dev
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -qq
 - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
 - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
 - sudo add-apt-repository -y ppa:boost-latest/ppa && sudo apt-get update -q && sudo apt-get install -y libboost1.55-all-dev
 - sudo apt-get install -qq libssl-dev libssh2-1-dev
 - sudo apt-get install -qq freeglut3 freeglut3-dev libglew1.5 libglew1.5-dev libglu1-mesa libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev

before_script:
 - chmod +x ./build_linux.sh 

script: ./build_linux.sh

deploy:
  provider: releases
  api_key: 
    secure: xafw00jYr9UVqFbl42oI3POGxS3UTNZAaqByeKK42bPZLEkw4hxoQM4HIIRvba0TnaTlUNwe93NdYY1g+2ScODQuECzrd4QBph17$
  file: ParaWorld/bin64/ParaEngineServer
  file:
    - "ParaWorld/bin64/liblua.so"
    - "ParaWorld/bin64/ParaEngineServer"
    - "ParaWorld/bin64/libluasql.so"
    - "ParaWorld/bin64/libsqlite.so"
    - "ParaWorld/bin64/libNPLMono2.so"
    - "ParaWorld/bin64/NPLMonoInterface.dll"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    all_branches: true
    repo: LiXizhi/NPLRuntime
    
